apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240131230007.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240131230007.0.0+build.02e9424
  releaseNotes: |
    Release v20240131230007.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-29-01-2024-10-12-33-597397718/where-for-dinner-search-my-apps-bundle@sha256:6b1fac393f95ba80479b5964931f4c504a22148303b8a4e5c8228846e9b59167
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

