apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240129110149.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240129110149.0.0+build.02e9424
  releaseNotes: |
    Release v20240129110149.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-29-01-2024-10-12-33-597397718/where-for-dinner-my-apps-bundle@sha256:8dee45415a248df2a9c8e268446942c88a4b4540ee3fcabbf7dcdcdcbe60a4ca
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

