apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20240131230006.0.0+build.02e9424
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20240131230006.0.0+build.02e9424
  releaseNotes: |
    Release v20240131230006.0.0+build.02e9424 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-29-01-2024-10-12-33-597397718/where-for-dinner-search-proc-my-apps-bundle@sha256:18a85de7d168c5d3448adbc16b8d38eeec354e46b264fd69ad8bc660d1ecbf4e
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

