apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search-proc.my-apps.tap.20240201165435.0.0+build.c5ac160
spec:
  refName: where-for-dinner-search-proc.my-apps.tap
  version: 20240201165435.0.0+build.c5ac160
  releaseNotes: |
    Release v20240201165435.0.0+build.c5ac160 of package where-for-dinner-search-proc.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-29-01-2024-10-12-33-597397718/where-for-dinner-search-proc-my-apps-bundle@sha256:20d1d0252ba2b000e301d3909f3d0862c80872f02f3be84fcd8fbcd28cf011b1
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

