apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.my-apps.tap.20240131135732.0.0+build.02e9424
spec:
  refName: where-for-dinner-availability.my-apps.tap
  version: 20240131135732.0.0+build.02e9424
  releaseNotes: |
    Release v20240131135732.0.0+build.02e9424 of package where-for-dinner-availability.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-29-01-2024-10-12-33-597397718/where-for-dinner-availability-my-apps-bundle@sha256:acd48f9d2a485ac3a1ae7a94fd5e232c8ac8d2ad96d200e25985e2c64bf59350
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

