apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240129110219.0.0+build.02e9424
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240129110219.0.0+build.02e9424
  releaseNotes: |
    Release v20240129110219.0.0+build.02e9424 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-29-01-2024-10-12-33-597397718/where-for-dinner-notify-my-apps-bundle@sha256:94d00ebab4f4e473a4ed3473ce612629e12e68ceb496c0d794dbd3b78eb50904
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

