apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240201165318.0.0+build.c5ac160
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240201165318.0.0+build.c5ac160
  releaseNotes: |
    Release v20240201165318.0.0+build.c5ac160 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-29-01-2024-10-12-33-597397718/where-for-dinner-notify-my-apps-bundle@sha256:184991a5d646c17fb82c4c94fc25afc535b5bb5c41ec832339429ccbc050b2db
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

